spring:
  application:
    name: yamyam-map

  datasource:
    url: jdbc:h2:mem:testdb;DATABASE_TO_UPPER=false;MODE=MYSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

jwt:
  secret: dGhpc2lzYXZlcnlzZWN1cmUzMmJ5dGVrZXlmb3JoczI1Ng==
  expiration: 3600000  # 1 hour in milliseconds

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
