spring:
  application:
    name: yamyam-map

  datasource:
    url: your_database_url
    username: your_database_username
    password: your_database_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  redis:
    host: localhost
    port: 6379

jwt:
  secret: your_jwt_secret_key
  expiration: 3600000  # 1 hour in milliseconds

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method