version: '3.8'

services:
  yamyam-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Seoul
    ports:
      - "${DB_PORT}:3306"

  yamyam-test-db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: yamyam-test
      MYSQL_USER: oz
      MYSQL_PASSWORD: password!
      MYSQL_ROOT_PASSWORD: password!
      TZ: Asia/Seoul
    ports:
      - "3337:3306"
